# Generated by Django 4.1.7 on 2023-02-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('description', models.CharField(max_length=2000, null=True, verbose_name='Описание товара')),
                ('image', models.TextField(verbose_name='Фото товара')),
                ('category', models.CharField(default='other', max_length=50, verbose_name='Категория')),
                ('amount', models.IntegerField(default=1, verbose_name='Остаток')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
