# Generated by Django 4.1.7 on 2023-03-13 12:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labwork_60', '0004_productincart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Phone number')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Amount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labwork_60.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labwork_60.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='labwork_60.OrderProducts', to='labwork_60.product'),
        ),
    ]
